# Generated by Django 5.2.3 on 2025-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='meal',
            field=models.CharField(choices=[('ALL', 'Все'), ('Breakfast', 'Завтрак'), ('Lunch', 'Обед'), ('Dinner', 'Ужин')], default=1, max_length=155, verbose_name='Прием Пищи'),
            preserve_default=False,
        ),
    ]
