# Generated by Django 5.2.3 on 2025-07-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_foods_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefs_name', models.CharField(max_length=155, verbose_name='Имена поворов')),
                ('chefs_photos', models.ImageField(upload_to='', verbose_name='Фото шефа')),
            ],
        ),
    ]
