# Generated by Django 5.2.3 on 2025-07-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
    ]
