# Generated by Django 5.2.3 on 2025-07-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_about_us_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='foods_title',
        ),
        migrations.AlterField(
            model_name='about_us',
            name='chefs_name',
            field=models.CharField(max_length=155, verbose_name='Имена поваров'),
        ),
    ]
