# Generated by Django 5.2.3 on 2026-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_foods_foods_title_alter_about_us_chefs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='chefs_photos',
            field=models.ImageField(upload_to='chefs/', verbose_name='Фото шефа'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(upload_to='foods/', verbose_name='Картинка еды'),
        ),
    ]
